export const actionType = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS'
}

export const pagination = {
    PAGE_SIZE: 5,
}

export const message = {
    SAVE_USER_SUCCESSFULLY: 'SAVE_USER_SUCCESSFULLY',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    DELETE_USER_SUCCESSFULLY: 'DELETE_USER_SUCCESSFULLY',
    UPDATE_USER_SUCCESSFULLY: 'UPDATE_USER_SUCCESSFULLY'
}